version: '3.7'

networks:
  alkemio_notifications_net:

services:
  alkemio_notifications:
    container_name: alkemio_notifications
    image: alkemio_notifications
    build: .
    networks:
      - alkemio_notifications_net
    restart: always
    command: npm run start
