export enum NotificationEventType {
  COMMUNITY_APPLICATION_CREATED = 'communityApplicationCreated',
  COMMUNITY_NEW_MEMBER = 'communityNewMember',
  COMMUNITY_INVITATION_CREATED = 'communityInvitationCreated',
  COMMUNITY_PLATFORM_INVITATION_CREATED = 'communityPlatformInvitationCreated',
  COMMUNITY_INVITATION_CREATED_VC = 'communityInvitationCreatedVC',
  COMMUNICATION_COMMENT_SENT = 'communicationCommentSent',
  COMMUNICATION_UPDATE_SENT = 'communicationUpdateSent',
  COMMUNICATION_COMMUNITY_MESSAGE = 'communicationCommunityMessage',
  COMMUNICATION_USER_MENTION = 'communicationUserMention',
  COLLABORATION_WHITEBOARD_CREATED = 'collaborationWhiteboardCreated',
  COLLABORATION_POST_CREATED = 'collaborationPostCreated',
  COLLABORATION_POST_COMMENT = 'collaborationPostComment',
  COLLABORATION_DISCUSSION_COMMENT = 'collaborationCommentOnDiscussion',
  COLLABORATION_CALLOUT_PUBLISHED = 'collaborationCalloutPublished',
  COMMENT_REPLY = 'commentReply',
  PLATFORM_USER_REGISTERED = 'platformUserRegistered',
  PLATFORM_USER_INVITED_TO_ROLE = 'platformUserInvitedToRole',
  PLATFORM_USER_REMOVED = 'platformUserRemoved',
  PLATFORM_GLOBAL_ROLE_CHANGE = 'platformGlobalRoleChange', 
  PLATFORM_SPACE_CREATED = 'platformSpaceCreated',
  PLATFORM_FORUM_DISCUSSION_COMMENT = 'platformForumDiscussionComment',
  PLATFORM_FORUM_DISCUSSION_CREATED = 'platformForumDiscussionCreated',
  ORGANIZATION_MESSAGE = 'organizationMessage',
  ORGANIZATION_MENTION = 'organizationMention',
  USER_MESSAGE = 'userMessage',

}
