export enum EmailTemplate {
  COMMUNITY_NEW_MEMBER_ADMIN = 'community.new.member.admin',
  COMMUNITY_NEW_MEMBER_MEMBER = 'community.new.member.member',
  COMMUNITY_USER_APPLICATION_APPLICANT = 'community.user.application.applicant',
  COMMUNITY_USER_APPLICATION_ADMIN = 'community.user.application.admin',
  COMMUNICATION_DISCUSSION_CREATED_ADMIN = 'communication.discussion.created.admin',
  COMMUNICATION_DISCUSSION_CREATED_MEMBER = 'communication.discussion.created.member',
  COMMUNICATION_UPDATE_ADMIN = 'communication.update.admin',
  COMMUNICATION_UPDATE_MEMBER = 'communication.update.member',
  COLLABORATION_REVIEW_SUBMITTED_ADMIN = 'collaboration.review.submitted.admin',
  COLLABORATION_REVIEW_SUBMITTED_REVIEWER = 'collaboration.review.submitted.reviewer',
  COLLABORATION_INTEREST_USER = 'collaboration.interest.user',
  COLLABORATION_INTEREST_ADMIN = 'collaboration.interest.admin',
  COLLABORATION_CARD_CREATED_ADMIN = 'collaboration.card.created.admin',
  COLLABORATION_CARD_CREATED_MEMBER = 'collaboration.card.created.member',
  COLLABORATION_CARD_COMMENT_MEMBER = 'collaboration.card.comment.member',
  COLLABORATION_CALLOUT_PUBLISHED_MEMBER = 'collaboration.callout.published.member',
  PLATFORM_USER_REGISTRATION_REGISTRANT = 'platform.user.registration.registrant',
  PLATFORM_USER_REGISTRATION_ADMIN = 'platform.user.registration.admin',
}
