name: Build & Deploy to Test on Azure

on:
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # checkout the repo
      - name: "Checkout GitHub Action"
        uses: actions/checkout@v3.0.2

      - name: "Login via Azure CLI"
        uses: azure/login@v1.4.7
        with:
          creds: ${{ secrets.AZURE_CRED_K8S_NEW }}

      - name: "Build and push image"
        uses: azure/docker-login@v1.0.1
        with:
          login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - run: |
          docker build -f Dockerfile . -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/alkemio-notifications:${{ github.sha }} -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/alkemio-notifications:latest
          docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/alkemio-notifications:${{ github.sha }}
      - uses: Azure/aks-set-context@v3.2
        with:
          cluster-name: k8s-test
          resource-group: res-grp-k8s-test

      - uses: Azure/k8s-create-secret@v4.0
        with:
          container-registry-url: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          container-registry-username: ${{ secrets.REGISTRY_USERNAME }}
          container-registry-password: ${{ secrets.REGISTRY_PASSWORD }}
          secret-name: alkemio-notifications-secret

      - uses: Azure/k8s-deploy@v4.10
        with:
          manifests: |
            service/manifests/25-notifications-deployment-dev.yaml
          images: |
            ${{ secrets.REGISTRY_LOGIN_SERVER }}/alkemio-notifications:${{ github.sha }}
          imagepullsecrets: |
            alkemio-notifications-secret
