export enum AlkemioErrorStatus {
  NOT_SUPPORTED = 'NOT_SUPPORTED',
  TEMPLATE_NOT_PROVIDED = 'TEMPLATE_NOT_PROVIDED',
  PAYLOAD_NOT_PROVIDED = 'PAYLOAD_BUILDER_NOT_PROVIDED',
  TEMPLATE_BUILDER_NOT_PROVIDED = 'TEMPLATE_BUILDER_NOT_PROVIDED',
  ROLES_NOT_PROVIDED = 'ROLES_NOT_PROVIDED',
  RULES_SET_NOT_FOUND = 'RULE_SET_NOT_FOUND',
}
