export enum EmailTemplate {
  USER_REGISTRATION_REGISTRANT = 'user.registration.registrant',
  USER_REGISTRATION_ADMIN = 'user.registration.admin',
  USER_APPLICATION_APPLICANT = 'user.application.applicant',
  USER_APPLICATION_ADMIN = 'user.application.admin',
  COMMUNICATION_DISCUSSION_CREATED_ADMIN = 'communication.discussion.created.admin',
  COMMUNICATION_DISCUSSION_CREATED_MEMBER = 'communication.discussion.created.member',
  COMMUNICATION_UPDATE_ADMIN = 'communication.update.admin',
  COMMUNICATION_UPDATE_MEMBER = 'communication.update.member',
  COMMUNITY_REVIEW_SUBMITTED_ADMIN = 'community.review.submitted.admin',
  COMMUNITY_REVIEW_SUBMITTED_REVIEWER = 'community.review.submitted.reviewer',
  COMMUNITY_NEW_MEMBER_ADMIN = 'community.new.member.admin',
  COMMUNITY_NEW_MEMBER_MEMBER = 'community.new.member.member',
  COMMUNITY_COLLABORATION_INTEREST_USER = 'community.collaboration.interest.user',
  COMMUNITY_COLLABORATION_INTEREST_ADMIN = 'community.collaboration.interest.admin',
  ASPECT_CREATED_ADMIN = 'aspect.created.admin',
  ASPECT_CREATED_MEMBER = 'aspect.created.member',
  ASPECT_COMMENT_CREATED_MEMBER = 'aspect.comment.created.member',
}
