export const NOTIFICATIONS_PROVIDER = 'NOTIFICATIONS';
export const TEMPLATE_PROVIDER = 'TEMPLATES';
export const ALKEMIO_CLIENT_PROVIDER = 'ALKEMIO_CLIENT';
export const ALKEMIO_CLIENT_ADAPTER = 'ALKEMIO_CLIENT_ADAPTER';
export const NOTIFICATION_RECEIVER_PROVIDER = 'NOTIFICATION_RECEIVER';
